import "./Inter/Inter-Black.ttf"
import "./Inter/Inter-Bold.ttf"
import "./Inter/Inter-ExtraBold.ttf"
import "./Inter/Inter-Light.ttf"
import "./Inter/Inter-ExtraLight.ttf"
import "./Inter/Inter-Medium.ttf"
import "./Inter/Inter-Regular.ttf"
import "./Inter/Inter-SemiBold.ttf"
import "./Inter/Inter-Thin.ttf"

import "./Noto_Sans_JP/NotoSansJP-Black.otf"
import "./Noto_Sans_JP/NotoSansJP-Bold.otf"
import "./Noto_Sans_JP/NotoSansJP-Light.otf"
import "./Noto_Sans_JP/NotoSansJP-Medium.otf"
import "./Noto_Sans_JP/NotoSansJP-Regular.otf"
import "./Noto_Sans_JP/NotoSansJP-Thin.otf"